### PR TITLE
Delayed postprocessing timeout logic

### LINKED ISSUE #103: Delayed postprocessing timeout logic
## Description

 > What is changing and why.  For example, what prompted this change?

Delayed postprocessing timeout logic is changing due to:
- Frames getting stuck in buffer indefinitely without being postprocessed if no new items arrive.
- Trigger needing to define additional steps to take in case of a timeout.

Solution includes:
- With each timeout, ending point for the processing window is widened, allowing all frames to eventually meet the processing threshold.
- A timeout policy function that will be defined by `DataHandlingModel` variants. (e.g. `TriggerDataHandlingModel`)

## Testing Suggestions

> For example, what steps would a reviewer use to see the change in action?

TODO

## Correlated Issues and/or PRs

> If multiple Issues or PRs are part of this change, list them here.  The sub-issue functionality in GitHub can also be used.

[Delayed postprocessing timeout logic #104](https://github.com/DUNE-DAQ/datahandlinglibs/pull/104)
[Delayed postprocessing timeout logic #416](https://github.com/DUNE-DAQ/trigger/pull/416)

## Useful Coordination

> List whatever coordination between developers or groups will be useful, such as the timing of merges or updating of documentation or updating of configurations

`TriggerDataHandlingModel<RDT, RHT, LBT, RPT, IDT>::invoke_postprocess_schedule_timeout_policy()` has to be implemented.

## Impact on Developers or Users

> For example, API changes or new run control commands

`// Actions postprocess scheduler takes if no data arrives in a configured time`
`DataHandlingModel<RDT, RHT, LBT, RPT, IDT>::invoke_postprocess_schedule_timeout_policy()`
`TriggerDataHandlingModel<RDT, RHT, LBT, RPT, IDT>::invoke_postprocess_schedule_timeout_policy()`

## Changes in System Behavior

> For example, changes in how data is drained from the system when a run is stopped

TODO

## Needed Changes in Testing

> For example, new regression tests that are needed, or instructions for special tests that should be run at EHN1

TODO

### PR DESCRIPTION
**Pull request by denizergonul**
- Items can get stuck in buffer without getting postprocessed if no new items arrive. To fix this, we implemented a timeout logic that takes into consideration how many timeouts occurred since an item has been waiting to get processed.
- Trigger has to define a policy on what to do in case of a timeout. For this, we introduced a new function in `DataHandlingModel` that will be overriden by `TriggerDataHandlingModel`. The function is called by postprocess scheduler.

https://github.com/DUNE-DAQ/trigger/pull/416

### CODE REVIEW

File: include/datahandlinglibs/models/detail/DataHandlingModel.hxx [hunk 1]
```diff
@@ -360,8 +356,26 @@ DataHandlingModel<RDT, RHT, LBT, RPT, IDT>::postprocess_schedule() {
       TLOG() << "***** First pass post processing *****";
     }
 
-    if (newest_ts - processed_element.get_timestamp() > m_processing_delay_ticks) {
-      end_win_ts = newest_ts - m_processing_delay_ticks;
+    now = std::chrono::system_clock::now();
```
Comment (alessandrothea) [inline include/datahandlinglibs/models/detail/DataHandlingModel.hxx]: This looks good

File: include/datahandlinglibs/models/detail/DataHandlingModel.hxx [hunk 2]
```diff
@@ -360,8 +356,26 @@ DataHandlingModel<RDT, RHT, LBT, RPT, IDT>::postprocess_schedule() {
...
+          end_win_ts = newest_ts - m_processing_delay_ticks;
+          postprocess = true;
+        }
+      }
+    }
+
+    if (postprocess) {
       auto start_iter = m_latency_buffer_impl->lower_bound(processed_element, false);
       processed_element.set_timestamp(end_win_ts);
       auto end_iter = m_latency_buffer_impl->lower_bound(processed_element, false);
```
Comment (alessandrothea) [inline include/datahandlinglibs/models/detail/DataHandlingModel.hxx]: Question: in case of timeouts, where `end_win_ts` >> `tail->get_timestamp()`, what will `lower_bound(processed_element, false)` return?

**Review by alessandrothea — COMMENTED** [review]
Looks good to me so far!

File: include/datahandlinglibs/models/detail/DataHandlingModel.hxx [hunk 3]
```diff
@@ -360,8 +356,26 @@ DataHandlingModel<RDT, RHT, LBT, RPT, IDT>::postprocess_schedule() {
...
 
-    if (newest_ts - processed_element.get_timestamp() > m_processing_delay_ticks) {
-      end_win_ts = newest_ts - m_processing_delay_ticks;
+    now = std::chrono::system_clock::now();
+
+    if (timeout) {      
+      ++m_num_post_processing_delay_max_waits;
+      ++consecutive_timeouts;
+      const timestamp_t timeout_accumulated = consecutive_timeouts * max_wait_in_ticks;      
+      end_win_ts = newest_ts - m_processing_delay_ticks + timeout_accumulated;
```
Comment (alessandrothea) [inline include/datahandlinglibs/models/detail/DataHandlingModel.hxx]: Suggestion for a possible optimization:
It would be better not to let `end_win_ts` to become too large, i.e. much larger than `tail().get_timestamp()`.
I would probably cap `timeout_accumulated` to `max_wait_in_ticks+m_processing_delay_ticks` (for instance) such that `end_win_ts=newest_ts+max_wait_in_ticks` at most.

@aeoranday @roland-sipos what do you think?

File: include/datahandlinglibs/models/detail/DataHandlingModel.hxx (hunk 2 above)
Comment (denizergonul) [reply include/datahandlinglibs/models/detail/DataHandlingModel.hxx]: If `lower_bound` can't find an element in the buffer, it returns `end()`, which allows processing the tail.

File: include/datahandlinglibs/models/detail/DataHandlingModel.hxx (hunk 3 above)
Comment (denizergonul) [reply include/datahandlinglibs/models/detail/DataHandlingModel.hxx]: Good point, I agree. Could also cap with simply `newest_ts + 1`?

Comment (alessandrothea) [reply include/datahandlinglibs/models/detail/DataHandlingModel.hxx]: Yeah, probably capping to `newest_ts + 1` is sufficient.
Actually, would `newest_ts` be enough? Since `lower_bound(processed_element,...)` will look for `(newest_ts, 0xffffff, ...)`, which is past `tail()`?

File: include/datahandlinglibs/models/DataHandlingModel.hpp [hunk 4]
```diff
@@ -132,6 +132,102 @@ class DataHandlingModel : public DataHandlingConcept
...
+      timestamp_t end_win_ts = 0;
+      std::chrono::time_point<std::chrono::system_clock> now;
+
+      if (timeout) {      
+        ++m_consecutive_timeouts;
+        timestamp_t timeout_accumulated = m_consecutive_timeouts * m_max_wait_in_ticks;  
+
+        // Cap to prevent end_win_ts from becoming unnecessarily large
+        timestamp_t timeout_cap = newest_ts + 1;
+        timeout_accumulated = std::min(timeout_accumulated, timeout_cap);
```
Comment (alessandrothea) [inline include/datahandlinglibs/models/DataHandlingModel.hpp]: I suspect that the timeout cap implemented like this won't really work.
`newest_ts` is counted from epoch, so...

Maybe the simplest option is something like:
```c++
end_win_ts = newest_ts - m_processing_delay_ticks + timeout_accumulated;
end_win_ts = std::min(end_win_ts, newest_ts + 1);
```

Comment (alessandrothea) [reply include/datahandlinglibs/models/DataHandlingModel.hpp]: Or even

```cpp
end_win_ts = newest_ts + std::min(timeout_accumulated- m_processing_delay_ticks, 1);
```

**Review by alessandrothea — CHANGES_REQUESTED** [review]
Looks very nice. Just one comment about the postprocessing timeout logic.

File: unittest/datahandlinglibs_DataHandlingModel_test.cxx [hunk 5]
```diff
@@ -0,0 +1,82 @@
...
+
+using ReadoutType = types::DUMMY_FRAME_STRUCT;
+
+BOOST_AUTO_TEST_CASE(datahandlinglibs_DataHandlingModel_PostprocessScheduleAlgorithm_timeout)
+{
+  std::atomic<bool> run_marker = true;
+
+  auto model =
+    unittest::MockDataHandlingModel<ReadoutType,
+                                    DefaultRequestHandlerModel<ReadoutType, SkipListLatencyBufferModel<ReadoutType>>,
```
Comment (denizergonul) [inline unittest/datahandlinglibs_DataHandlingModel_test.cxx:76]: Do we want the same test with a queue?

File: include/datahandlinglibs/models/DataHandlingModel.hpp [hunk 6]
```diff
@@ -132,6 +133,105 @@ class DataHandlingModel : public DataHandlingConcept
...
+          } else {
+            TLOG_DEBUG(TLVL_WORK_STEPS) << "Not ready to postprocess (m_processing_delay_ticks is greater)";
+            return 0;
+          }
+        } else {
+          TLOG_DEBUG(TLVL_WORK_STEPS) << "Not ready to postprocess (too fast)";
+          return 0;
+        }
+      }
+
```
Comment (alessandrothea) [inline include/datahandlinglibs/models/DataHandlingModel.hpp:223]: Ok, this is just an optimization, but maybe still worth considering:
After a few timeouts, `end_win_ts` will settle on  `newest_ts+1`, so maybe one could check here if
`end_win_ts >= m_unprocessed_element.get_timestamp()` and if so, stop the processing here.
@denizergonul let me know what you think.

Comment (denizergonul) [reply include/datahandlinglibs/models/DataHandlingModel.hpp:223]: I suggest `m_processed_up_to.get_timestamp() >= newest_ts + 1`

File: unittest/datahandlinglibs_DataHandlingModel_test.cxx (hunk 5 above)
Comment (denizergonul) [reply unittest/datahandlinglibs_DataHandlingModel_test.cxx:76]: No... delayed postprocessing only makes sense for skip list.

**Comment by denizergonul** [comment]
What's your final opinion on `RDT m_processed_up_to{}`?

File: include/datahandlinglibs/models/DataHandlingModel.hpp (hunk 6 above)
Comment (denizergonul) [reply include/datahandlinglibs/models/DataHandlingModel.hpp:223]: (so we don't even calculate `end_win_ts` )

**Review by alessandrothea — APPROVED** [review]
LGTM
